name: Build

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
          - os: ubuntu-latest
            android: true
          - os: macos-latest
            ios: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      run: rustup update

    # Install Android NDK on Ubuntu
    - name: Install Android NDK (Ubuntu only)
      if: matrix.android == 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip -d $HOME
        echo "ANDROID_NDK_HOME=$HOME/android-ndk-r23b" >> $GITHUB_ENV
        echo "PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    # Install Rust target for Android
    - name: Add Android target
      if: matrix.android == 'true'
      run: rustup target add aarch64-linux-android

    # Build for Android
    - name: Build for Android
      if: matrix.android == 'true'
      run: cargo build --release --target aarch64-linux-android

    # Install Rust target for iOS
    - name: Add iOS target
      if: matrix.ios == 'true'
      run: rustup target add aarch64-apple-ios

    # Build for iOS
    - name: Build for iOS
      if: matrix.ios == 'true'
      run: cargo build --release --target aarch64-apple-ios

    # Regular build steps for other platforms
    - name: Build
      if: matrix.android != 'true' && matrix.ios != 'true'
      run: cargo build --release

    # Cleanup steps for Windows
    - name: Clean up target directory (Windows only)
      if: runner.os == 'Windows'
      run: |
        Remove-Item -Path "target\release\build" -Recurse -Force
        Remove-Item -Path "target\release\deps" -Recurse -Force
        Remove-Item -Path "target\release\examples" -Recurse -Force
        Remove-Item -Path "target\release\incremental" -Recurse -Force
        Remove-Item -Path "target\CACHEDIR.TAG" -Force
        Remove-Item -Path "target\.rustc_info.json" -Force
        Remove-Item -Path "target\release\.fingerprint" -Recurse -Force
        Remove-Item -Path "target\release\.cargo-lock" -Force

    # Cleanup steps for macOS and Linux
    - name: Clean up target directory (macOS and Linux only)
      if: runner.os != 'Windows'
      run: |
        rm -rf target/release/build
        rm -rf target/release/deps
        rm -rf target/release/examples
        rm -rf target/release/incremental
        rm -f target/CACHEDIR.TAG
        rm -f target/.rustc_info.json
        rm -rf target/release/.fingerprint
        rm -f target/release/.cargo-lock

    # Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: target/
