name: Build

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
    - run: cargo build --release
    - run: rmdir /s /q target/release/build
    - run: rmdir /s /q target/release/deps
    - run: rmdir /s /q target/release/examples
    - run: rmdir /s /q target/release/incremental
    - uses: actions/upload-artifact@v4
      with:
        path: target/release/
